Foreman 3.10 branching build updates
theforeman/foreman-packaging pull request #10453
Opened 2024-02-20 19:51 UTC by pcreech

2024-02-21 18:26 UTC, ekohl requested changes
The repo names also contain nightly.

2024-02-21 18:26 UTC, ekohl commented on repoclosure/yum.conf
> +baseurl=https://stagingyum.theforeman.org/katello/3.10/el8/x86_64/
```suggestion
baseurl=https://stagingyum.theforeman.org/katello/4.12/el8/x86_64/
```

2024-02-21 18:26 UTC, ekohl commented on repoclosure/yum.conf
> +[el8-katello-3.10-staging]
```suggestion
[el8-katello-4.12-staging]
```

2024-02-21 18:26 UTC, ekohl commented on repoclosure/yum.conf
> +[el9-katello-3.10-staging]
```suggestion
[el9-katello-4.12-staging]
```

2024-02-21 18:26 UTC, ekohl commented on repoclosure/yum.conf
> +baseurl=https://stagingyum.theforeman.org/katello/3.10/el9/x86_64/
```suggestion
baseurl=https://stagingyum.theforeman.org/katello/4.12/el9/x86_64/
```

2024-02-22 14:31 UTC, pcreech commented
@ekohl should be resolved now

2024-02-22 15:33 UTC, ekohl approved these changes

2024-02-22 15:33 UTC, merged