Refs #37212 - retire foreman_setup plugin
theforeman/foreman-packaging pull request #10470
Opened 2024-02-28 10:32 UTC by ekohl

2024-02-28 18:51 UTC, evgeni requested changes

2024-02-28 18:51 UTC, evgeni commented on packages/foreman/foreman-obsolete-packages/foreman-obsolete-packages.spec
> +- Obsolete foreman_setup
this should be a 1.7 IMHO

2024-03-26 12:18 UTC, ekohl commented
Update. https://github.com/theforeman/foreman-installer/pull/926 is the installer side.

2024-04-29 07:15 UTC, evgeni approved these changes

2024-04-29 07:21 UTC, merged