move rubygem-jquery-ui-rails package to katello
theforeman/foreman-packaging pull request #11004
Opened 2024-07-11 12:40 UTC by MariaAga

for https://github.com/Katello/katello/pull/10982 and https://github.com/theforeman/foreman/pull/10142
I ran:
`./remove_package rubygem-jquery-ui-rails` 
`./add_gem_package.sh jquery-ui-rails foreman_plugin katello`

2024-07-11 16:34 UTC, ekohl requested changes
Technically I'd prefer to use `git mv` on the package directory **if** we're moving it. Then it also belongs in the `katello` comps, not `foreman-plugins`.

But I said **if**. I'd be OK with keeping this in Foreman's repo for now. Moving it creates some churn and it's really just a build-time dependency that we want to get rid of anyway. Obviously, this wouldn't be the first time we say that and then take forever to execute on it. Still, I think it's acceptable.

I think what @m-bucher meant is that currently the dependency is listed in `foreman.spec` but should be in `rubygem-katello.spec`.

2024-07-12 13:16 UTC, MariaAga commented
Thanks @ekohl, is this the correct way to do it?

2024-07-12 14:01 UTC, ekohl requested changes
I always use https://github.com/ekohl/theforeman-plumbing/blob/master/fm-packaging-update-deps to update the dependencies. Once we drop EL8 in Foreman 3.13 then we can use https://github.com/theforeman/foreman-packaging/pull/8414 to automatically generate those sections based on the sources.

I wouldn't mind it if we merged the PRs and I can submit the update PRs for you. Ideally this whole complex area is going away and there's little point in learning it now.

2024-07-12 14:45 UTC, MariaAga commented on packages/foreman/foreman/foreman.spec
> -BuildRequires: (rubygem(jquery-ui-rails) >= 6.0 with rubygem(jquery-ui-rails) < 7.0)
I made https://github.com/theforeman/foreman/pull/10142 to remove it

2024-07-12 14:46 UTC, MariaAga commented on packages/katello/rubygem-katello/rubygem-katello.spec
> +# end specfile assets BuildRequires
Not sure if I should keep both BuildRequires and Requires then?

2024-07-30 18:33 UTC, ekohl commented on packages/katello/rubygem-katello/rubygem-katello.spec
> +# end specfile assets BuildRequires
For `rubygem-katello.spec` (and all `rubygem-*.spec` really) it should autogenerate `Requires`, so no need for that.

2024-08-06 11:19 UTC, MariaAga commented on packages/katello/rubygem-katello/rubygem-katello.spec
> +# end specfile assets BuildRequires
removed the `Requires`

2024-10-18 09:06 UTC, MariaAga commented
@ekohl Thanks for the review, how can I progress this?

2024-10-31 14:08 UTC, adamruzicka commented
[test rpm-copr]

2024-10-31 16:31 UTC, MariaAga commented
split into https://github.com/theforeman/foreman-packaging/pull/11416 https://github.com/theforeman/foreman-packaging/pull/11417

2024-10-31 16:31 UTC, closed without merging