Update rubygem-foreman_scc_manager to 3.1.0 Foreman 3.10
theforeman/foreman-packaging pull request #11083
Opened 2024-08-02 11:20 UTC by nadjaheitmann

(cherry picked from commit 18d3693e50d1bea6347c5a4d4e2def45c5584edf)

2024-08-02 15:11 UTC, ekohl requested changes
I couldn't fast forward merge, so the commit ID became 2e892f702155512bd581aa753e0465a9628aa1e5. I also don't see a cherry pick for 3.11.

2024-08-05 07:45 UTC, nadjaheitmann commented
> I couldn't fast forward merge, so the commit ID became [2e892f7](https://github.com/theforeman/foreman-packaging/commit/2e892f702155512bd581aa753e0465a9628aa1e5). I also don't see a cherry pick for 3.11.

Fixed the commit ID and opened a PR for 3.11, thanks for pointing out.

2024-08-07 10:40 UTC, nadjaheitmann commented
@ekohl Why is it showing 'Stale branch' label?

2024-08-15 13:29 UTC, ehelms approved these changes

2024-08-15 13:30 UTC, merged