Add and Update foreman_supervisory_authority dependencies
theforeman/foreman-packaging pull request #11157
Opened 2024-08-22 11:06 UTC by ochnerd

Add base64-0.2.0 as dependency for llhttp-ffi
Update http to 5.2.0
Update http-form_data to 2.3.0
Add llhttp-ffi-0.5.0 as dependency for http

2024-08-22 12:59 UTC, dgoetz commented
ok to test

2024-08-22 13:14 UTC, ochnerd commented
I used the script but my Mac kind of complaint about something. I check that and push again, thanks for testing!

2024-08-22 13:28 UTC, ochnerd commented
@dgoetz , should ./add_gem_package.sh add them to package_manifest.yaml?

2024-08-22 13:37 UTC, dgoetz commented
Yes, there is a function `add_to_manifest` which maps the repository to the corresponding section of the manifest and the functions `add_gem_to_all_comps` and `add_gem_to_comps` ensure packages are added to matching comps.
The manifest is used as base for obal (and all other tooling) resulting in the linting error.

2024-08-22 15:14 UTC, dgoetz commented
Repoclosure now fails with

```
Error: Repoclosure ended with unresolved dependencies (3) across 1 packages.
package: rubygem-http-5.2.0-1.el8.noarch from repo0
  unresolved deps (3):
    (rubygem(base64) >= 0.1 with rubygem(base64) < 1)
    (rubygem(http-form_data) >= 2.2 with rubygem(http-form_data) < 3)
    (rubygem(llhttp-ffi) >= 0.5.0 with rubygem(llhttp-ffi) < 0.6)
```

So with base64 being 0.2.0, llhttp-ffi 0.5.0, and http-form_data 2.3.0, this is a problem of order. Not sure if you need to split up the PR once more or having the packages in single commits in correct order would be enough (this is what I typically do).

2024-08-23 05:53 UTC, ochnerd commented
Ahh I see the problem. If I think about the order I will probably need to open multiple PR when I understand correctly the dependencies need to already be in the repository. So Single PRs it is. I would leace this PR Open, include the links to the new PRs and close it after the new PRs have been merged.

2024-08-23 06:03 UTC, ochnerd commented
base64 PR https://github.com/theforeman/foreman-packaging/pull/11164 has no dependencies

2024-09-03 13:33 UTC, ekohl requested changes
I think you may be right we need all dependencies satisfied before repoclosure can work. I thought we grouped them, but now that I take a closer look we don't.

2024-09-03 13:33 UTC, ekohl commented on packages/plugins/rubygem-base64/rubygem-base64.spec
Please don't add base64. https://github.com/theforeman/foreman-packaging/pull/11119 works at documenting how you should deal with it. I left other comments below with more specific examples.

2024-09-03 13:33 UTC, ekohl commented on packages/plugins/rubygem-http/rubygem-http.spec
> +%setup -q -n  %{gem_name}-%{version}
And then drop the base64 dependency here:
```suggestion
%setup -q -n  %{gem_name}-%{version}

%gemspec_remove_dep -g base64 '~> 0.1'
```

2024-09-03 13:33 UTC, ekohl commented on packages/plugins/rubygem-http/rubygem-http.spec
> +%{gem_instdir}/.rubocop
```suggestion
%exclude %{gem_instdir}/.rubocop
```

2024-09-03 13:33 UTC, ekohl commented on packages/plugins/rubygem-llhttp-ffi/rubygem-llhttp-ffi.spec
> +# does not really align with any other package
I don't see what's so different. This looks fairly standard to me for a gem with native extensions.

2024-09-03 13:33 UTC, ekohl commented on comps/comps-foreman-el8.xml
I'm not sure why it gets sorted very different. We try to set the locale for consistent sorting but perhaps you don't have that locale installed?
https://github.com/theforeman/foreman-packaging/blob/9aeba42bc76b99db734b9fef3f7c4fa0eb55c3ac/comps_doc.sh#L6

2024-09-03 13:49 UTC, ochnerd commented on packages/plugins/rubygem-base64/rubygem-base64.spec
Because of the dependency Issues I split this PR into the other 3 (I should close this PR i think): 
https://github.com/theforeman/foreman-packaging/pull/11165
https://github.com/theforeman/foreman-packaging/pull/11166
https://github.com/theforeman/foreman-packaging/pull/11167

2024-09-16 07:38 UTC, ochnerd commented
Closed in favor for splitted PR 
https://github.com/theforeman/foreman-packaging/pull/11165
https://github.com/theforeman/foreman-packaging/pull/11166
https://github.com/theforeman/foreman-packaging/pull/11167

2024-09-16 07:38 UTC, closed without merging