Add rubygem-llhttp-ffi package
theforeman/foreman-packaging pull request #11165
Opened 2024-08-23 06:15 UTC by ochnerd

Add llhttp-ffi 0.5.0 as dependency for http 5.2.0

2025-02-25 10:47 UTC, ekohl requested changes
Apologies for the long delay in reviewing.

2025-02-25 10:47 UTC, ekohl commented on comps/comps-foreman-plugins-el8.xml
This needs to be el9 now

2025-03-13 07:20 UTC, ochnerd commented on comps/comps-foreman-plugins-el8.xml
Done, Thanks for Reviewing!

2025-03-20 11:43 UTC, ekohl commented
ok to test

2025-05-11 13:02 UTC, ekohl commented
> If we go that route then I think we can go another route:
> 
>     * package `rubygems-llhttp`

https://github.com/theforeman/foreman-packaging/pull/12008
 
>     * patch out the gem requirement in `http`

https://github.com/theforeman/foreman-packaging/pull/12009

>     * drop the now unused  `ffi-compiler` from our packaging

https://github.com/theforeman/foreman-packaging/pull/12010

2025-05-12 06:20 UTC, ochnerd commented
@ekohl thanks for the idea. It sounds better than using the ffi version.
I was swamped with the zeitwerk changes in our plugins and forgot about this issue.

2025-05-14 09:06 UTC, closed without merging