Bump rubygem-http to 5.2.0-1
theforeman/foreman-packaging pull request #11167
Opened 2024-08-23 06:24 UTC by ochnerd

Needs:
base64 PR https://github.com/theforeman/foreman-packaging/pull/11164 has no dependencies
llhttp-ffi PR https://github.com/theforeman/foreman-packaging/pull/11165 has dependencies which can be resolved
http-form_data PR https://github.com/theforeman/foreman-packaging/pull/11166 has no dependencies

2024-08-23 16:13 UTC, ekohl requested changes
Please prefer `base64` from default gems on Ruby < 3.3, just like we did in https://github.com/theforeman/foreman-packaging/pull/10490.

2024-08-26 05:39 UTC, ochnerd commented
Oh ok, i will add the changes and use the default gems. But https://github.com/theforeman/foreman-packaging/pull/11166 and https://github.com/theforeman/foreman-packaging/pull/11165 need to be resolved first because they are needed.

2024-08-26 18:38 UTC, ekohl commented
> Oh ok, i will add the changes and use the default gems. But #11166 and #11165 need to be resolved first because they are needed.

If they aren't build dependencies (and in this case I think they aren't) you can include them in the same PR).

2024-09-03 13:21 UTC, ochnerd commented
@ekohl , can really include them in the same PR if it failed like in https://github.com/theforeman/foreman-packaging/pull/11157#issuecomment-2304953287 mentioned?

2024-09-03 13:34 UTC, ekohl commented
I think you may be right that we need all dependencies.

For some reason, CI didn't run at all on this PR so it looks like nothing is wrong.

2025-02-25 10:43 UTC, ekohl requested changes

2025-02-25 10:43 UTC, ekohl commented on packages/plugins/rubygem-http/rubygem-http.spec
> +Requires: (rubygem(base64) or ruby-default-gems < 3.4)
This should be outside of the `specfile generated dependencies` block because it's not generated. It'll get removed on the next update

2025-03-13 07:27 UTC, ochnerd commented on packages/plugins/rubygem-http/rubygem-http.spec
> +Requires: (rubygem(base64) or ruby-default-gems < 3.4)
I moved it above the block. Is this ok or should it be somewhere else in the spec?

2025-05-14 09:25 UTC, ekohl commented
Obsoleted by https://github.com/theforeman/foreman-packaging/pull/12009

2025-05-14 09:25 UTC, closed without merging