Enforce tmpfiles on foreman
theforeman/foreman-packaging pull request #5757
Opened 2020-09-04 07:24 UTC by lzap

Temporary files are created too late, we need to make sure they are
created as the package installs.

2020-09-04 09:02 UTC, lzap commented
Wait, it does not work:

```
rpmspec -P specfile
...
systemd-tmpfiles --replace=/usr/lib/tmpfiles.d/foreman.conf --create - <<SYSTEMD_INLINE_EOF || : 
 
SYSTEMD_INLINE_EOF
```

2020-09-04 09:08 UTC, ekohl requested changes
Reference: https://github.com/systemd/systemd/blob/5b49641015adcc7e8edbb9e8e54d5ac5ddf3bf52/src/core/macros.systemd.in#L136-L154

However, it looks like the `%tmpfiles_create_package` macro is not present on EL7. That only has `%tmpfiles_create`:
```console
# grep tmpfiles /usr/lib/rpm/macros.d/macros.systemd   
%_tmpfilesdir /usr/lib/tmpfiles.d
%tmpfiles_create() \
systemd-tmpfiles --create %{?*} >/dev/null 2>&1 || : \
```

2020-09-04 09:41 UTC, lzap commented
It works as expected:

```
[root@nightly ~]# ll /run/foreman -lad
drwxr-xr-x. 2 foreman foreman 40 Sep  3 16:21 /run/foreman

[root@nightly ~]# yum upgrade *rpm
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

...

Updated:
  foreman.noarch 0:2.3.0-0.4.develop.20200904092354gitd444989.el7          foreman-debug.noarch 0:2.3.0-0.4.develop.20200904092354gitd444989.el7 
  foreman-libvirt.noarch 0:2.3.0-0.4.develop.20200904092354gitd444989.el7 
Complete!

[root@nightly ~]# ll /run/foreman -lad
drwxr-x---. 2 foreman foreman 40 Sep  4 11:27 /run/foreman
```

2020-09-04 09:48 UTC, ekohl approved these changes

2020-09-04 09:54 UTC, ekohl commented
Can someone from @theforeman/packaging take a look as well?

2020-09-04 13:56 UTC, pcreech approved these changes
ACK

2020-09-04 13:57 UTC, merged

2020-09-07 07:15 UTC, tbrisker commented
@lzap once the other PR is accepted, please cherry pick both commits back to all stable branches

2020-09-07 09:34 UTC, lzap commented
* 2.2 CP https://github.com/theforeman/foreman-packaging/pull/5766
* 2.1 CP https://github.com/theforeman/foreman-packaging/pull/5767
* 2.0 CP https://github.com/theforeman/foreman-packaging/pull/5768