Add nodejs-optimize-css-assets-webpack-plugin package
theforeman/foreman-packaging pull request #5980
Opened 2020-11-11 22:58 UTC by amirfefer

2020-11-27 08:31 UTC, evgeni commented on comps/comps-foreman-rhel7.xml
> +      <packagereq type="default">nodejs-optimize-css-assets-webpack-plugin</packagereq>
```suggestion
      <packagereq type="default">tfm-nodejs-optimize-css-assets-webpack-plugin</packagereq>
```

and then this needs proper sorting :)

2020-11-27 08:32 UTC, evgeni commented
could you also please omit the ordering changes around google-cloud-env?

2020-11-27 08:33 UTC, evgeni commented on comps/comps-foreman-rhel7.xml
> +      <packagereq type="default">nodejs-optimize-css-assets-webpack-plugin</packagereq>
and `nodejs-optimize-css-assets-webpack-plugin` (without the `tfm-` prefix) needs adding to `comps-foreman-el8.xml` (the script currently fails to do that for two comps files :()

2020-11-27 08:34 UTC, evgeni commented on rel-eng/tito.props
> +  nodejs-optimize-css-assets-webpack-plugin
same needs to be added to `foreman-nightly-el8`, our scripts fail to do so :(

2020-11-27 08:34 UTC, evgeni requested changes
comments inline

2020-12-09 23:42 UTC, amirfefer commented
Thanks @evgeni !
Updated

2021-01-05 12:57 UTC, amirfefer commented
Rebased

2021-01-05 13:50 UTC, merged