Fixes #31393 - Drop sysvinit scripts on Debian
theforeman/foreman-packaging pull request #6045
Opened 2020-11-25 13:34 UTC by ekohl

2020-11-26 10:19 UTC, lzap approved these changes
Looks okay to me. It built so... let's ship it!

2020-11-27 11:16 UTC, evgeni requested changes

2020-11-27 11:16 UTC, evgeni commented on debian/buster/foreman-proxy/foreman-proxy.preinst
> +dpkg-maintscript-helper rm_conffile /etc/default/foreman-proxy 2.4.0~ -- "$@"
```suggestion
dpkg-maintscript-helper rm_conffile /etc/default/foreman-proxy 2.4.0~ -- "$@"

#DEBHELPER#
```

2020-11-27 11:16 UTC, evgeni commented on debian/bionic/foreman-proxy/foreman-proxy.preinst
> +dpkg-maintscript-helper rm_conffile /etc/default/foreman-proxy 2.4.0~ -- "$@"
```suggestion
dpkg-maintscript-helper rm_conffile /etc/default/foreman-proxy 2.4.0~ -- "$@"

#DEBHELPER#
```

2020-11-27 16:37 UTC, ekohl commented
Updated

2020-11-30 10:09 UTC, evgeni approved these changes

2020-11-30 10:10 UTC, merged