Update rubygem-net-ldap to 0.17.0
theforeman/foreman-packaging pull request #6150
Opened 2020-12-16 14:06 UTC by ezr-ondrej

Bump to newest version.
- [ ] Needs to wait for https://github.com/theforeman/foreman/pull/8205

2020-12-16 14:40 UTC, tbrisker requested changes
Looks like you missed a few: error: 
```
    File not found: /builddir/build/BUILDROOT/rubygem-net-ldap-0.17.0-1.el8.noarch/usr/share/gems/gems/net-ldap-0.17.0/Gemfile
    File not found: /builddir/build/BUILDROOT/rubygem-net-ldap-0.17.0-1.el8.noarch/usr/share/gems/gems/net-ldap-0.17.0/net-ldap.gemspec
    File not found: /builddir/build/BUILDROOT/rubygem-net-ldap-0.17.0-1.el8.noarch/usr/share/gems/gems/net-ldap-0.17.0/script

2021-01-06 14:12 UTC, ezr-ondrej commented
[test rpm]

2021-01-06 14:31 UTC, ezr-ondrej commented
:green_apple:

2021-01-27 12:31 UTC, evgeni approved these changes

2021-01-27 12:31 UTC, merged