[RPM/2.3] - Add nodejs-redhat-cloud-services-frontend-components package
theforeman/foreman-packaging pull request #6157
Opened 2020-12-22 14:22 UTC by laviro

2021-01-04 12:03 UTC, ShimShtein commented
[test]

2021-01-04 14:21 UTC, evgeni requested changes
I've requested changes in #6158 -- will need to be ported here too.

2021-01-04 16:12 UTC, laviro commented
Thanks @evgeni !! updated also here :)

2021-01-25 12:12 UTC, evgeni commented on rel-eng/tito.props
> +  rubygem-zest
can you clear out that whitespace? :)

2021-01-26 08:32 UTC, ShimShtein commented
@evgeni, done.

2021-01-26 09:17 UTC, evgeni approved these changes

2021-01-26 09:19 UTC, merged