Add nodejs-redhat-cloud-services-frontend-components package
theforeman/foreman-packaging pull request #6158
Opened 2020-12-22 14:27 UTC by laviro

2021-01-04 12:31 UTC, laviro commented
@theforeman/packaging can we get this in? :)
also opened a PR to `rpm/2.3` which is also green: https://github.com/theforeman/foreman-packaging/pull/6157

2021-01-04 14:14 UTC, evgeni commented
@laviro you can, just not over Christmas ;-)

2021-01-04 14:20 UTC, evgeni reviewed
please add el8 bits, then it's good to go

2021-01-04 14:20 UTC, evgeni commented on rel-eng/tito.props
> +  nodejs-redhat-cloud-services-frontend-components
please also add to `foreman-nightly-el8`

2021-01-04 14:20 UTC, evgeni commented on comps/comps-foreman-rhel7.xml
> +      <packagereq type="default">nodejs-redhat-cloud-services-frontend-components</packagereq>
```suggestion
      <packagereq type="default">tfm-nodejs-redhat-cloud-services-frontend-components</packagereq>
```
(and then please sort again)

`nodejs-redhat-cloud-services-frontend-components` needs to be added to `comps-foreman-el8.xml`

2021-01-04 14:24 UTC, evgeni requested changes
see previous comments

2021-01-04 16:11 UTC, laviro commented
Thanks @evgeni !! updated

2021-01-25 12:11 UTC, evgeni approved these changes

2021-01-25 12:11 UTC, merged