Update rubygem-highline to 2.0.3
theforeman/foreman-packaging pull request #6169
Opened 2021-01-06 19:45 UTC by ehelms

2021-01-06 19:45 UTC, ehelms commented
Planning to use these scratch builds for some testing first

2021-01-06 21:09 UTC, ehelms commented
I tested a few actions from foreman-maintain, change-hostname and hammer to verify this version of highline would work. I ran into no issues. There may be some still possibly, but I think we should take in the change and see if we encounter them in nightly.

2021-01-07 07:36 UTC, evgeni approved these changes

2021-01-07 12:54 UTC, ekohl requested changes

2021-01-07 12:54 UTC, ekohl commented on packages/foreman/rubygem-kafo/rubygem-kafo.spec
> +Requires: %{?scl_prefix}rubygem(highline) < 2.1.0
Looks like the proper update procedure wasn't followed. Updating to 6.2.0 should have updated this
```suggestion
Requires: %{?scl_prefix}rubygem(highline) < 3.0.0
```

It has the correct markings so `bump_rpm.sh` should have caught this. If you used obal to bump and it doesn't do this, IMHO it means obal should not be used to bump gem RPMs until it's fixed to update dependencies.

2021-01-07 13:54 UTC, ekohl approved these changes
Given currently nightly is red, I'm wondering if we should first make it green to keep the number of possibly breaking changes small. Other than that :+1:

2021-01-18 10:32 UTC, evgeni commented
Foreman nightlies have been green for a while, and with 2.4 stabilization approaching, we should get that either in, or wait longer, so I vote for in.

2021-01-18 10:32 UTC, merged