Sp acd001
theforeman/foreman-packaging pull request #6199
Opened 2021-01-19 10:01 UTC by sbernhard

2021-01-29 08:22 UTC, evgeni requested changes
this needs a rebase for latest changes to package_manifest.yml

also the package needs adding to the EL8 configs (comps, tito.props) -- our scripts currently don't do that automatically :(

also, some inline comments about the proper spec layout for SCL'ed proxy

2021-01-29 08:22 UTC, evgeni commented on comps/comps-foreman-plugins-rhel7.xml
> +      <packagereq type="default">rubygem-smart_proxy_acd-doc</packagereq>
the smart proxy is SCL'ed these days too, so it should be `tfm-rubygem-…` and then also sorted accordingly ;)

2021-01-29 08:22 UTC, evgeni commented on comps/comps-foreman-el8.xml
> -      <packagereq type="default">rubygem-google-cloud-env-doc</packagereq>
imho this change is noise :)

2021-01-29 08:22 UTC, evgeni commented on comps/comps-foreman-rhel7.xml
> -      <packagereq type="default">tfm-rubygem-google-cloud-env-doc</packagereq>
imho this change is noise :)

2021-01-29 08:22 UTC, evgeni commented on package_manifest.yaml
> +    rubygem-smart_proxy_acd: {}
this should be in `plugin_scl_packages` -- does `add_gem_package` need an update here?

2021-01-29 08:22 UTC, evgeni commented on packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
> +%global foreman_proxy_min_version 1.25
there is no such thing as 1.25 -- did you mean 2.0?

2021-01-29 08:22 UTC, evgeni commented on packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
> +%endif
```suggestion
Requires: %{?scl_prefix}rubygem(smart_proxy_dynflow_core) >= 0.2.2
Requires: %{?scl_prefix}rubygem(smart_proxy_acd_core)
```

2021-01-29 08:22 UTC, evgeni commented on packages/plugins/rubygem-smart_proxy_acd/rubygem-smart_proxy_acd.spec
> +%{?scl:Obsoletes: rubygem-%{gem_name}}
not required for a new plugin

2021-01-29 08:22 UTC, evgeni commented on rel-eng/tito.props
> +  rubygem-smart_proxy_acd
needs to go into scl

2021-02-01 13:07 UTC, sbernhard commented
thank you very much @evgeni for your help! let me know if its ok now.

2021-02-08 10:28 UTC, evgeni approved these changes

2021-02-08 10:33 UTC, merged

2021-02-08 10:33 UTC, evgeni commented
@sbernhard if you want that for 2.4, please cherrypick :)