Update foreman_ansible to 6.1.0
theforeman/foreman-packaging pull request #6205
Opened 2021-01-21 08:58 UTC by adamruzicka

2021-01-25 12:43 UTC, evgeni requested changes
Should this be 6.1.1 instead?

2021-01-25 12:56 UTC, adamruzicka commented
/me sighs

Of course it should

2021-01-25 13:13 UTC, evgeni approved these changes

2021-01-26 09:29 UTC, evgeni commented
[test packaging]

2021-01-26 10:04 UTC, merged