Add foreman_webhooks 0.0.1 - DEB
theforeman/foreman-packaging pull request #6218
Opened 2021-01-25 09:37 UTC by lzap

For plugin updates, please indicate which repos this should be built into:

* Nightly
* 2.3

2021-01-25 12:35 UTC, lzap commented
It's failing with `LoadError: Error loading the 'postgresql' Active Record adapter. Missing a gem it depends on? pg is not part of the bundle. Add it to your Gemfile.` and I can't figure out why. Honestly, I took discovery gem and just replaced the name. It should use the null-db driver.... hmm.

2021-01-25 13:09 UTC, evgeni requested changes
reviewed with @baboon92, you have confused dpkg :)

2021-01-25 13:09 UTC, evgeni commented on plugins/ruby-foreman-webhooks/debian/changelog
> +ruby-foreman-discovery (0.0.1) unstable; urgency=low
```suggestion
ruby-foreman-webhooks (0.0.1) unstable; urgency=low
```

dpkg fails to properly unpack that source package, and thus you get wild errors nobody can understand :)

2021-01-25 13:31 UTC, ekohl commented on plugins/ruby-foreman-webhooks/debian/copyright
> +Copyright: 2013 Red Hat Inc. <foreman-dev@googlegroups.com>
That's a while back.

2021-01-25 15:05 UTC, lzap commented
Shoot me in my head, but we detect plugin name from a CHANGELOG :-) Wow, well. Okay! Love it.

2021-01-26 09:29 UTC, lzap commented
The package looks good on my system.

2021-01-27 11:54 UTC, evgeni requested changes
minor nitpicks, ack when adressed

2021-01-27 11:54 UTC, evgeni commented on plugins/ruby-foreman-webhooks/debian/compat
> +8
```suggestion
11
```

2021-01-27 11:54 UTC, evgeni commented on plugins/ruby-foreman-webhooks/debian/control
> +Build-Depends: debhelper (>= 8.0.0), foreman (>= 1.23.0~rc1), foreman-assets(>= 1.23.0~rc1), foreman-nulldb (>= 1.23.0~rc1)
```suggestion
Build-Depends: debhelper (>= 11~), foreman (>= 1.23.0~rc1), foreman-assets(>= 1.23.0~rc1), foreman-nulldb (>= 1.23.0~rc1)
```

the RPM says it needs Foreman 2.3, here you say 1.23, what's correct? :)

2021-01-27 11:54 UTC, evgeni commented on plugins/ruby-foreman-webhooks/debian/control
> +Depends: ${misc:Depends}, bundler, foreman (>= 1.23.0~rc1)
same, should this be 2.3?

2021-02-08 12:49 UTC, lzap commented on plugins/ruby-foreman-webhooks/debian/control
> +Depends: ${misc:Depends}, bundler, foreman (>= 1.23.0~rc1)
Oh yes.

2021-02-08 12:52 UTC, lzap commented
Updated the version to 2.3, squashed your changes, thanks.

2021-02-08 14:55 UTC, evgeni approved these changes

2021-02-08 15:12 UTC, merged