Remove rbovirt package
theforeman/foreman-packaging pull request #6222
Opened 2021-01-25 20:49 UTC by shiramax

2021-01-27 10:16 UTC, tbrisker approved these changes
Leaving it for @evgeni to do the actual cleanup from koji

2021-01-27 10:39 UTC, evgeni requested changes
the ovirt provision plugin seems to still depend on this?
```
packages/plugins/rubygem-ovirt_provision_plugin/rubygem-ovirt_provision_plugin.spec:Requires: %{?scl_prefix}rubygem(rbovirt) >= 0.0.27
```

also please remove rbovirt from the following files:
* comps/comps-foreman-el8.xml
* comps/comps-foreman-rhel7.xml
* package_manifest.yaml
* rel-eng/tito.props

2021-01-27 11:42 UTC, tbrisker commented
Looks like ovirt_provision plugin probably requires an update to the rpm spec, the gemspec doesn't rely on rbovirt: https://github.com/theforeman/ovirt_provision_plugin/blob/master/ovirt_provision_plugin.gemspec

2021-03-04 14:13 UTC, tbrisker commented on packages/plugins/rubygem-ovirt_provision_plugin/rubygem-ovirt_provision_plugin.spec
> +Release:    2%{?foremandist}%{?dist}
This also needs a changelog entry below, and i'm not sure if it can be done in the same pr or not

2021-03-08 09:23 UTC, tbrisker commented on packages/plugins/rubygem-ovirt_provision_plugin/rubygem-ovirt_provision_plugin.spec
> +* Wed Mon 08 2021 Shira Maximov <shiramaximov@gmail.com> 2.0.3-2
```suggestion
* Mon Mar 08 2021 Shira Maximov <shiramaximov@gmail.com> 2.0.3-2
```

2021-03-09 08:31 UTC, tbrisker approved these changes
Thanks @shiramax ! @evgeni any further comments?

2021-03-12 06:44 UTC, evgeni approved these changes

2021-03-12 06:46 UTC, merged