Bump @theforeman/vendor
theforeman/foreman-packaging pull request #6290
Opened 2021-02-08 13:26 UTC by xprazak2

2021-02-09 10:18 UTC, evgeni commented
you can't bump a package and its buildrequires in the same PR, so you'll have to split off the foreman change.

also, any reason not to update @theforeman/builder too?

2021-02-09 12:05 UTC, xprazak2 commented
Thanks, I updating it [separately](https://github.com/theforeman/foreman-packaging/pull/6301), seems like I got a silent failure before and builder did not get updated.

2021-02-09 19:09 UTC, evgeni requested changes
please also update theforeman/builder requiremenets

2021-02-10 11:10 UTC, evgeni commented on packages/foreman/foreman/foreman.spec
> +BuildRequires: %{?scl_prefix}npm(@theforeman/builder) < 8.0.0
your math is seriously off

2021-02-10 11:30 UTC, xprazak2 commented on packages/foreman/foreman/foreman.spec
> +BuildRequires: %{?scl_prefix}npm(@theforeman/builder) < 8.0.0
Maybe I should start drinking coffee.

2021-02-10 11:32 UTC, evgeni approved these changes

2021-02-10 11:49 UTC, evgeni requested changes
```
Requires: %{?scl_prefix}npm(@theforeman/builder) >= 6.0.0
Requires: %{?scl_prefix}npm(@theforeman/builder) < 7.0.0
```
(line 459/460) still needs updating

2021-02-11 11:33 UTC, xprazak2 commented
Updated.

2021-02-11 11:52 UTC, evgeni approved these changes

2021-02-11 11:52 UTC, merged