Bump ACD and Smart Proxy for ACD
theforeman/foreman-packaging pull request #6434
Opened 2021-03-15 12:32 UTC by sbernhard

2021-03-18 06:43 UTC, evgeni requested changes
can you please fix the changelog entry? it's good to go then.

2021-03-18 06:43 UTC, evgeni commented on packages/plugins/rubygem-foreman_acd/rubygem-foreman_acd.spec
> +* Mon Mar 15 2021 Bernhard Suttner,,, 0.6.0-1
```suggestion
* Mon Mar 15 2021 Bernhard Suttner <suttner@atix.de> 0.6.0-1
```

2021-03-18 06:48 UTC, evgeni requested changes
oh, and tito

2021-03-18 06:48 UTC, evgeni commented on rel-eng/tito.props
> +  rubygem-smart_proxy_acd_core
you also need to add these to foreman-plugins-2.4-rhel7

2021-03-24 09:02 UTC, sbernhard commented
I guess, I missed the flight for 2.4.0 :-(

2021-03-24 11:42 UTC, evgeni commented
> I guess, I missed the flight for 2.4.0 :-(

Luckily, for you, plugins are released independently, so you only missed being there on day 0.

2021-03-24 11:45 UTC, evgeni approved these changes

2021-03-24 11:45 UTC, merged