Update foreman-tasks up to 4.0.0
theforeman/foreman-packaging pull request #6451
Opened 2021-03-18 10:01 UTC by adamruzicka

- Update foreman-tasks to 3.0.4
- Update foreman-tasks to 3.0.5
- Update ruby-foreman-tasks to 4.0.0

2021-03-18 11:34 UTC, evgeni requested changes

2021-03-18 11:34 UTC, evgeni commented on plugins/ruby-foreman-tasks/debian/changelog
> +ruby-foreman-tasks (3.0.5-1) stable; urgency=low
```suggestion
ruby-foreman-tasks (4.0.0-1) stable; urgency=low
```

2021-03-18 11:34 UTC, evgeni commented on plugins/ruby-foreman-tasks/debian/changelog
> +ruby-foreman-tasks (4.0.0-1) stable; urgency=low
```suggestion
ruby-foreman-tasks (3.0.5-1) stable; urgency=low
```

2021-03-18 11:35 UTC, evgeni commented
damn, this was also broken in `deb/develop` and I didn't notice

2021-03-18 11:58 UTC, adamruzicka commented
Soo, should I fix it in develop first and then cp it?

2021-04-09 07:16 UTC, evgeni commented
develop fix in https://github.com/theforeman/foreman-packaging/pull/6518

2021-04-09 12:46 UTC, evgeni approved these changes

2021-04-09 12:47 UTC, merged