Update foreman-fog-proxmox 0.13.3
theforeman/foreman-packaging pull request #6458
Opened 2021-03-18 14:19 UTC by tristanrobert

- fixes debian/rules syntax

(cherry picked from commit 6449ad0385e7645d8134c05965d64dc5359a4781)

 * 2.4

2021-03-18 15:25 UTC, tristanrobert commented
`bundle exec rake plugin:apipie:cache[foreman_fog_proxmox]` in debian/rules does not render anything. So `/var/lib/foreman/public/apipie-cache/plugin/foreman_fog_proxmox` is empty and not created. So is the issue. There is no  differences with files changed in #6457 except the branches deb/2.4 and deb/dev. i don't see how to fix it. Any ideas @evgeni ?

2021-03-18 15:48 UTC, evgeni commented
Why do you always pick the funny parts here? :)

I'll have a look and come back to you

2021-03-19 06:43 UTC, evgeni commented
[test packaging]

2021-03-19 09:08 UTC, tristanrobert commented
> Why do you always pick the funny parts here? :)
> 
> I'll have a look and come back to you

Sorry ! Thank you for your help.

2021-03-19 09:14 UTC, tristanrobert commented
Same issue: https://ci.theforeman.org/job/packaging_build_deb_plugin/arch=x86,label=debian,os=bionic/736/console

2021-03-25 14:41 UTC, evgeni requested changes
based on the discussion and tests in #6481, you should be able to drop the installation of the apipie cache and it should build fine

I am still investigating why it was needed on nightly, but until then… nuke it

2021-03-25 14:41 UTC, evgeni commented on plugins/ruby-foreman-fog-proxmox/debian/install
> +apipie-cache/foreman_fog_proxmox var/lib/foreman/public/apipie-cache/plugin
```suggestion
```

2021-03-25 14:41 UTC, evgeni commented on plugins/ruby-foreman-fog-proxmox/debian/rules
> +		cp -rp /var/lib/foreman/public/apipie-cache/plugin/$(PLUGIN) ./apipie-cache/
```suggestion
```

2021-03-26 14:38 UTC, evgeni approved these changes

2021-03-26 14:38 UTC, merged