Update rubygem-mini_portile2 to 2.5.1
theforeman/foreman-packaging pull request #6582
Opened 2021-04-30 01:48 UTC by ehelms

2021-04-30 02:21 UTC, ehelms commented
[test rpm]

2021-04-30 12:46 UTC, ekohl requested changes

2021-04-30 12:46 UTC, ekohl commented on packages/foreman/rubygem-mini_portile2/rubygem-mini_portile2.spec
> +%{gem_instdir}/.github
I think this should be excluded.

2021-04-30 12:46 UTC, ekohl commented on packages/foreman/rubygem-mini_portile2/rubygem-mini_portile2.spec
> +%{gem_instdir}/SECURITY.md
```suggestion
%doc %{gem_instdir}/SECURITY.md
```

2021-04-30 13:43 UTC, ehelms commented
Addresses comments and adds a commit to update gem2rpm scl template

2021-04-30 13:50 UTC, ehelms commented
Note once this goes in the current nokogiri dependencies will be broken, so this will need to be coordinated with https://github.com/theforeman/foreman-packaging/pull/6583 such that they are merged close together. My testing locally with mock indicates the nokogiri PR should build once this and https://github.com/theforeman/foreman-packaging/pull/6581 are present.

2021-05-18 15:19 UTC, ehelms commented
This will need to be reviewed and timed with https://github.com/theforeman/foreman-packaging/pull/6583 also being approved. The rubygem-racc requirement for nokogiri has been merged and built.

2021-05-18 15:24 UTC, ekohl approved these changes

2021-05-26 12:19 UTC, merged