add optimize-css-assets-webpack-plugin
theforeman/foreman-packaging pull request #6731
Opened 2021-06-01 15:38 UTC by amirfefer

Supported Versions:

 * Nightly

2021-06-01 19:44 UTC, tbrisker commented
@amirfefer you need to bump the release and add a changelog entry

2021-06-02 10:57 UTC, tbrisker commented
looks like an actual build error now related to the change:
```
Error: Cannot find module 'cssnano'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports.env (/builddir/build/BUILD/foreman-2.6.0-develop/config/webpack.config.js:216:23)
    at handleFunction (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/prepareOptions.js:26:13)
    at prepareOptions (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/lib/prepareOptions.js:11:13)
    at requireConfig (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/bin/convert-argv.js:98:14)
    at /opt/theforeman/tfm/root/usr/lib/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/opt/theforeman/tfm/root/usr/lib/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

2021-06-07 07:29 UTC, tbrisker commented
@amirfefer please update again to include cssnano

2021-06-07 14:36 UTC, tbrisker requested changes
Please update the commit message to match the current content

2021-06-07 14:36 UTC, tbrisker commented on packages/foreman/foreman/foreman.spec
> +BuildRequires: %{?scl_prefix}npm(cssnano) < 4.1.1
This doesn't match the version in core: https://github.com/theforeman/foreman/blob/develop/package.json#L43
Also, it's missing from the `Requires` section below

2021-06-07 14:36 UTC, tbrisker commented on packages/foreman/foreman/foreman.spec
> +- Update depdendencies cssnano
How about:
```suggestion
- Update NPM dependencies
```

2021-06-08 08:17 UTC, tbrisker commented
@amirfefer the other comments still need fixing, and the versions still don't match what is in the package.json

2021-06-09 13:07 UTC, amirfefer commented
@tbrisker, thanks 👍 
updated

2021-06-09 18:33 UTC, tbrisker approved these changes

2021-06-09 18:33 UTC, merged