Rpm/develop hammer cli 3.0.0
theforeman/foreman-packaging pull request #6980
Opened 2021-08-04 15:00 UTC by ofedoren

@ekohl

Supported Versions:

 * Nightly

2021-08-04 15:21 UTC, ekohl requested changes
Same comments for the other spec.

2021-08-04 15:21 UTC, ekohl commented on packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
> -%global prereleasesource pre.develop
You can comment this

2021-08-04 15:21 UTC, ekohl commented on packages/foreman/rubygem-hammer_cli/rubygem-hammer_cli.spec
> -%global prerelease %{?prereleasesource:.}%{?prereleasesource}
Please keep this

2021-08-04 15:32 UTC, ofedoren commented
@ekohl, updated. Did I understand you right?..

2021-08-04 15:49 UTC, ekohl reviewed
Yes, you understood me right, but I think this is actually an edge case. For nightly packages we don't release the GA build to nightly. What I think is right is if we get to the point where we branch, then update `rpm/develop` to `3.1.0-develop` (including hammer) and then update to 3.0.0 GA in `rpm/3.0`. Does that make sense?

2021-08-04 18:08 UTC, upadhyeammit commented
> Yes, you understood me right, but I think this is actually an edge case. For nightly packages we don't release the GA build to nightly. What I think is right is if we get to the point where we branch, then update `rpm/develop` to `3.1.0-develop` (including hammer) and then update to 3.0.0 GA in `rpm/3.0`. Does that make sense?

Agree, can't see better way to handle this.

2021-08-05 11:49 UTC, tbrisker commented
IIUC we agreed to stick with nightly hammer builds in rpm/develop, closing. If I misunderstood feel free to reopen.

2021-08-05 11:49 UTC, closed without merging