Add rubygem-msgpack-rails package
theforeman/foreman-packaging pull request #7116
Opened 2021-09-21 19:09 UTC by jlsherrill

2021-09-21 19:48 UTC, evgeni requested changes

2021-09-21 19:48 UTC, evgeni commented on packages/foreman/rubygem-msgpack-rails/rubygem-msgpack-rails.spec
> +License: FIXME
Please do ;)

2021-09-21 19:48 UTC, evgeni commented on packages/foreman/rubygem-msgpack-rails/rubygem-msgpack-rails.spec
> +Requires: %{?scl_prefix}rubygem(msgpack)
I think this lives in plugins right now, and would need moving

2021-09-28 19:45 UTC, jlsherrill commented
closing as this was solved other ways in dynflow itself

2021-09-28 19:45 UTC, closed without merging