Fixes #33580 - Suggest new --puppet-server-foreman-url with hostname …
theforeman/foreman-packaging pull request #7140
Opened 2021-09-28 23:05 UTC by wbclark

…change

2021-09-29 18:57 UTC, wbclark commented
I think I see why this is breaking:

https://github.com/theforeman/obal/blob/ead56f57e7e3da5763482e3ede3143b458974190/obal/data/modules/rpmspec_changelog_check.py#L45-L47

It expects a specifically formatted changelog entry for the release bump

2021-09-30 09:55 UTC, ekohl requested changes
:+1: for the change in general

2021-09-30 09:55 UTC, ekohl commented on packages/katello/katello/katello.spec
> +* Tue Sep 28 2021 William Bradford Clark <wclark@redhat.com> 4.3.0-0.2master
```suggestion
* Tue Sep 28 2021 William Bradford Clark <wclark@redhat.com> 4.3.0-0.2.master
```

2021-09-30 18:25 UTC, wbclark commented
> +1 for the change in general

Fixed the typo... Thank you!

2021-09-30 20:28 UTC, ekohl approved these changes

2021-09-30 20:29 UTC, merged