Add rubygem-foreman_kernel_care package
theforeman/foreman-packaging pull request #7193
Opened 2021-10-21 15:42 UTC by maccelf

Add [foreman_kernel_care](https://github.com/maccelf/foreman_kernel_care) plugin

2021-10-21 22:00 UTC, ekohl commented
ok to test

2021-11-29 12:45 UTC, Odilhao commented
[test rpm]

2022-02-25 15:58 UTC, ares commented
Is there anything blocking this PR? rpm seems to build
[test rpm] to get fresh results

2022-02-25 16:27 UTC, adamruzicka requested changes
Because the plugin depends on Katello, it needs to be bundled in katello repos.

2022-02-25 16:27 UTC, adamruzicka commented on comps/comps-foreman-plugins-el8.xml
> +      <packagereq type="default">rubygem-foreman_kernel_care</packagereq>
This needs to go into `comps/comps-katello-el8.xml`

2022-02-25 16:27 UTC, adamruzicka commented on comps/comps-foreman-plugins-rhel7.xml
> +      <packagereq type="default">tfm-rubygem-foreman_kernel_care</packagereq>
`comps/comps-katello-el8.xml`

2022-02-25 16:27 UTC, adamruzicka commented on package_manifest.yaml
> +    rubygem-foreman_kernel_care: {}
This needs to go in `katello_packages` section

2022-02-25 16:27 UTC, adamruzicka commented on rel-eng/tito.props
> +  rubygem-foreman_kernel_care
This needs to go into `katello-nightly-el{7,8}`

2022-02-28 07:26 UTC, adamruzicka commented
Most likely the whole package directory needs to be in `packages/katello` instead of `packages/plugins`, sorry for not pointing that out previously

2022-02-28 10:22 UTC, adamruzicka commented
As far as I can tell there is nothing more left to be done here. The failures seem to be caused by katello moving to a newer version of pulp_rpm_client in [1,2]

[1] - https://github.com/Katello/katello/pull/9976
[2] - https://github.com/theforeman/foreman-packaging/pull/7621

2022-02-28 10:36 UTC, maccelf commented
@adamruzicka okay, thank you very much

2022-03-01 15:03 UTC, maccelf commented
@adamruzicka now we are waiting for the release of Katello right?

2022-03-03 08:26 UTC, adamruzicka commented
That's my understanding, yes

2022-03-23 14:22 UTC, maccelf commented
@adamruzicka Now this PR can be merged ?

2022-03-23 14:27 UTC, adamruzicka commented
I don't see why not, but I don't have necessary permissions here. @zjhuntin maybe?

2022-03-31 14:44 UTC, evgeni commented
Doing the @theforeman/packaging job again…

```console
evgeni@tanso ~ % koji add-pkg --owner kojiadm katello-nightly-el8 rubygem-foreman_kernel_care         
Adding 1 packages to tag katello-nightly-el8
evgeni@tanso ~ % koji add-pkg --owner kojiadm katello-nightly-rhel7 tfm-rubygem-foreman_kernel_care 
Adding 1 packages to tag katello-nightly-rhel7
```

2022-03-31 14:45 UTC, merged

2022-03-31 14:53 UTC, maccelf commented
Awesome, thanks very much