Update salt to 15.0.0
theforeman/foreman-packaging pull request #7577
Opened 2022-02-14 13:15 UTC by sbernhard

2022-02-18 08:22 UTC, sbernhard commented
Did I forget something? Don't know why the tests are red.

2022-02-22 16:25 UTC, zjhuntin commented
[test deb]

2022-02-22 17:19 UTC, zjhuntin commented
[test deb]

2022-02-22 20:04 UTC, ekohl requested changes
Looks like you missed a file that the [update script](https://github.com/theforeman/foreman-packaging/blob/deb/develop/scripts/update_package.rb) did catch. See https://github.com/theforeman/foreman-packaging/pull/7609 for that result.

2022-03-11 08:35 UTC, evgeni commented
[test deb]

2022-03-11 08:37 UTC, evgeni commented
[test deb]

2022-03-11 08:42 UTC, evgeni commented on plugins/ruby-foreman-salt/debian/control
> +Build-Depends: debhelper (>= 8.0.0), foreman-assets (>= 3.1.0~rc1), foreman (>= 3.1.0~rc1), ruby-foreman-deface, ruby-foreman-tasks (>= 5.1.0), ruby-foreman-remote-execution (>= 4.4.0-1)
```suggestion
Build-Depends: debhelper (>= 8.0.0), foreman-assets (>= 3.1.0~rc1), foreman (>= 3.1.0~rc1), foreman-nulldb (>= 3.1.0~rc1), ruby-foreman-deface, ruby-foreman-tasks (>= 5.1.0), ruby-foreman-remote-execution (>= 4.4.0-1)
```

no nulldb, no build ;)

2022-03-11 08:43 UTC, evgeni commented on plugins/ruby-foreman-salt/debian/control
> +Build-Depends: debhelper (>= 8.0.0), foreman-assets (>= 3.1.0~rc1), foreman (>= 3.1.0~rc1), ruby-foreman-deface, ruby-foreman-tasks (>= 5.1.0), ruby-foreman-remote-execution (>= 4.4.0-1)
seems you have not enabled "allow changes by maintainers" or I would have just committed that change now, so that we can move on?

2022-03-11 09:14 UTC, evgeni approved these changes

2022-03-11 09:14 UTC, merged