Fixes #34801 - update foreman-protector file paths
theforeman/foreman-packaging pull request #7819
Opened 2022-04-22 13:41 UTC by upadhyeammit

2022-04-25 07:27 UTC, upadhyeammit commented
> if I am correct with what i see then compilation is happening,
> 
> ```
>  bytecode_compilation_path=./usr/lib/yum-plugins/foreman-protector.py
> + failure=0
> ```
> 
> However I dont see **pycache** in /usr/lib/yum-plugins/ even if I try to install old package on EL7 system, not sure why it did not complain earlier?

I misread the code, originally __pycache__ was not expected to be on EL7,
~~~
%if 0%{?rhel} > 7
%{yumplugindir}/__pycache__/foreman-protector.cpython*
%endif
~~~

2022-04-25 14:28 UTC, evgeni commented on packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec
> +%global dnfplugindir %{_prefix}/lib%{nil}/python3.6/site-packages/dnf-plugins
```suggestion
%global dnfplugindir %{python3_sitelib}/dnf-plugins

2022-04-25 14:29 UTC, evgeni requested changes
one nitpick, otherwise good to go

2022-04-26 14:01 UTC, evgeni approved these changes

2022-04-26 14:01 UTC, merged