Update rubygem-foreman_webhooks to 3.0.3
theforeman/foreman-packaging pull request #8004
Opened 2022-06-01 12:56 UTC by ofedoren

Supported Versions:

 * Nightly
 * 3.3
 * 3.2

2022-06-01 14:13 UTC, dgoetz requested changes

2022-06-01 14:13 UTC, dgoetz commented on packages/plugins/rubygem-foreman_webhooks/rubygem-foreman_webhooks.spec
> +BuildRequires: %{?scl_prefix}npm(@theforeman/builder) < 9.0.0
This upper boundary is preventing the build as the current version of it is 10.1.0. This probably needs to be lifted in the gems package.json as the dependencies are created from there.

2022-06-03 13:41 UTC, ofedoren commented
@dgoetz, thanks, updated.

2022-06-03 13:53 UTC, dgoetz approved these changes
Not sure if the dependency should be relaxed so much, but from a packaging perspective it looks fine and the tests are green, so going to merge.

2022-06-03 13:53 UTC, merged