Updated hammer_cli_foreman_webhooks to 0.0.3
theforeman/foreman-packaging pull request #8012
Opened 2022-06-01 13:43 UTC by ofedoren

Supported Versions:

 * Nightly
 * 3.3

2022-06-03 14:30 UTC, ehelms commented
[test deb]

2022-07-06 14:54 UTC, ekohl requested changes
There's a merge conflict now.

2022-08-29 11:41 UTC, ekohl commented
[test deb]

2022-09-13 16:10 UTC, ehelms commented
[test deb]

2022-10-18 08:46 UTC, evgeni commented on dependencies/focal/hammer_cli_foreman_webhooks/changelog
> +ruby-hammer-cli-foreman-webhooks (0.0.3-1) stable; urgency=low
```suggestion
ruby-hammer-cli-foreman-webhooks (0.0.4-1) stable; urgency=low

  * 0.0.4 released

 -- Evgeni Golov <evgeni@debian.org>  Tue, 18 Oct 2022 10:44:53 +0200

ruby-hammer-cli-foreman-webhooks (0.0.3-1) stable; urgency=low
```

2022-10-18 09:17 UTC, evgeni commented
needs https://github.com/theforeman/foreman-packaging/pull/8596

2022-10-18 09:22 UTC, evgeni commented
which is now built, so
[test deb]

2022-10-18 09:30 UTC, merged