Add rubygem-foreman_netbox package
theforeman/foreman-packaging pull request #8021
Opened 2022-06-02 11:43 UTC by dgoetz

2022-06-03 07:09 UTC, dgoetz commented
And it is green now!

2022-06-03 08:06 UTC, evgeni requested changes
The min version needs adjustment (and the comment above it can go away then).

Otherwise lgtm

2022-06-03 08:18 UTC, dgoetz commented on packages/plugins/rubygem-foreman_netbox/rubygem-foreman_netbox.spec
> +%global foreman_min_version FIXME
I forgot it again! :-( Fixed now!

2022-06-03 08:21 UTC, evgeni reviewed
ACK

I don't have access to koji right now, so can't add the pkg and merge, but someone else might get to it later ;)

2022-06-03 08:22 UTC, evgeni approved these changes

2022-06-10 09:17 UTC, evgeni commented
Really, nobody cared to finish this off? :disappointed: 

```console
% koji add-pkg --owner kojiadm foreman-plugins-nightly-el8 rubygem-foreman_netbox   
Adding 1 packages to tag foreman-plugins-nightly-el8
% koji add-pkg --owner kojiadm foreman-plugins-nightly-rhel7 tfm-rubygem-foreman_netbox
Adding 1 packages to tag foreman-plugins-nightly-rhel7
```

2022-06-10 09:17 UTC, merged