Add hammer-cli-foreman-google-0.0.1
theforeman/foreman-packaging pull request #8634
Opened 2022-10-25 17:25 UTC by ofedoren

2022-10-26 06:48 UTC, evgeni commented on dependencies/bullseye/hammer_cli_foreman_google/control
> +Uploaders: Oleh Fedorenko <ofedoren@redhat.com>
```suggestion
Maintainer: Oleh Fedorenko <ofedoren@redhat.com>
```

2022-10-26 06:49 UTC, evgeni commented on dependencies/bullseye/hammer_cli_foreman_google/control
> +Vcs-Browser: https://salsa.debian.org/ruby-team/ruby-hammer-cli-foreman-google
```suggestion
```

2022-10-26 06:49 UTC, evgeni commented on dependencies/bullseye/hammer_cli_foreman_google/salsa-ci.yml
> +---
this file can be removed, we don't use Debian's CI system

2022-10-26 06:50 UTC, evgeni requested changes
some minor comments, as we don't use Debian's infrastructure, otherwise LGTM

(I commented only on bullseye, but the changes apply equally to both)

2022-10-30 17:41 UTC, ofedoren commented
Thanks, @evgeni, updated.

2022-10-30 17:45 UTC, evgeni approved these changes

2022-10-30 17:46 UTC, merged