Require sd_notify for systemd integration support from Puma
theforeman/foreman-packaging pull request #8660
Opened 2022-10-27 17:03 UTC by ehelms

I debated if this should just be added to Puma itself as a requirement. As it's only required if the service using Puma implement systemd support which is driven by our implementation in foreman rather than Puma itself.

On nearly all standard installation, a foreman-proxy is installed alongside Foreman which results in the `sd_notify` gem being present. However, we have places like our puppet acceptance tests that test Foreman in isolation and lack this support. I observed, for example, that foreman.service started timing out on start on https://github.com/theforeman/puppet-katello/pull/457. I see the same behaviour locally, but not when I install rubygem-sd_notify.

2022-10-27 19:19 UTC, ekohl requested changes
Technically it's only needed for the `foreman-service` package. I think https://github.com/theforeman/foreman/commit/9b0652fed9f86fd429e237ce359422a1dba14a2a shouldn't have dropped the dependency.

2022-10-27 19:22 UTC, ekohl commented
Oh, it should be in https://github.com/theforeman/foreman/blob/develop/bundler.d/service.rb now.

2022-10-28 11:41 UTC, ekohl commented
https://github.com/theforeman/foreman/pull/9488 does that.

2022-10-28 12:58 UTC, ekohl approved these changes
I hijacked your PR to reflect the changes to Foreman itself.

2022-10-28 12:59 UTC, ehelms commented
Gonna have to start charging you a fee for taking over my PRs :laughing:

2022-10-28 13:05 UTC, merged