Update rubygem-fog-vsphere to 3.6.0
theforeman/foreman-packaging pull request #8841
Opened 2022-12-14 15:26 UTC by chris1984

@ekohl here is the packaging pr for the new fog-vsphere gem

2022-12-14 15:36 UTC, ekohl requested changes
Besides the build failure (which is caused by changes in the `%files` section), you should also package rbvmomi2 because repoclosure will fail on that once you fix the build failure. That can be done in the same PR using `./add_gem_package.sh rbvmomi2 default foreman foreman-el8`.

2022-12-14 18:28 UTC, chris1984 commented
@ekohl looks like it's failing since rbvmomi2 is not in a list somewhere that obal lint is checking, I will look to see where else it needs added in the meantime till I hear back from you.

2022-12-14 18:37 UTC, chris1984 commented
Figured it out, had to add it to the package_manifest

2023-01-02 10:31 UTC, ekohl commented
Looks like the logs were rotated so [test rpm]

2023-01-02 10:33 UTC, ekohl requested changes

2023-01-02 10:33 UTC, ekohl commented on packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec
> +Version: 3.6.0
Looking at https://github.com/theforeman/foreman-packaging/pull/8856 you're missing some updates to the minimum Ruby version. Are you using `./bump_rpm.sh` to do updates?

2023-01-03 17:13 UTC, ekohl requested changes
You also need to reflect the changed files in fog-vsphere:
```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/rubygem-fog-vsphere-3.6.0-1.el8.noarch
error: Installed (but unpackaged) file(s) found:
   /usr/share/gems/gems/fog-vsphere-3.6.0/.github/workflows/ruby.yml
    File not found: /builddir/build/BUILDROOT/rubygem-fog-vsphere-3.6.0-1.el8.noarch/usr/share/gems/gems/fog-vsphere-3.6.0/.travis.yml
    Installed (but unpackaged) file(s) found:
   /usr/share/gems/gems/fog-vsphere-3.6.0/.github/workflows/ruby.yml
```

Please squash this in the right commits.

2023-01-11 14:38 UTC, chris1984 commented
@ekohl Do you know why this is not building? I fixed the rebase like you suggested so that part is fine now.

2023-01-11 14:43 UTC, ekohl commented
> You also need to reflect the changed files in fog-vsphere:
> 
> ```
> Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/rubygem-fog-vsphere-3.6.0-1.el8.noarch
> error: Installed (but unpackaged) file(s) found:
>    /usr/share/gems/gems/fog-vsphere-3.6.0/.github/workflows/ruby.yml
>     File not found: /builddir/build/BUILDROOT/rubygem-fog-vsphere-3.6.0-1.el8.noarch/usr/share/gems/gems/fog-vsphere-3.6.0/.travis.yml

To fix that you'll need to drop this:

https://github.com/theforeman/foreman-packaging/blob/09755ad90f84b2c117b153c17f8011b9a555ed78/packages/foreman/rubygem-fog-vsphere/rubygem-fog-vsphere.spec#L53

>     Installed (but unpackaged) file(s) found:
>    /usr/share/gems/gems/fog-vsphere-3.6.0/.github/workflows/ruby.yml
> ```

And to fix this you'll need a a similar `%exclude %{gem_instdir}/.github`. Do mind that you keep it sorted, so insert it around `.gitignore`.

2023-01-23 17:05 UTC, ekohl commented
@chris1984 can we move this forward? Or should I submit a replacement PR that resolves it? For now I've held that back, but this really needs to get in.

2023-01-23 17:42 UTC, chris1984 commented
Will fix it up today

2023-01-23 18:23 UTC, ekohl approved these changes
Looks good. Waiting for CI to complete.

2023-01-23 18:26 UTC, merged