Update rubygem-foreman_scc_manager to 2.2.0 Foreman 3.3
theforeman/foreman-packaging pull request #8928
Opened 2023-01-11 11:48 UTC by nadjaheitmann

(cherry picked from commit d2a38afd5f86a545ab53f20378cdfb8d219653f8)

2023-01-12 11:17 UTC, ekohl requested changes
Could you pick all commits?

2023-01-12 11:48 UTC, nadjaheitmann commented
> Could you pick all commits?

Done.

2023-01-12 11:54 UTC, nadjaheitmann commented on packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
> +%global foreman_min_version 3.4
This should actually be 3.1, not 3.4.

2023-01-12 12:27 UTC, ekohl requested changes

2023-01-12 12:27 UTC, ekohl commented on packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
> +BuildRequires: rubygems-devel
Also redundant from the lines above
```suggestion
```

2023-01-12 12:32 UTC, nadjaheitmann commented on packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
> +%global foreman_min_version 3.4
I will keep that in mind

2023-01-12 13:19 UTC, ekohl commented on packages/katello/rubygem-foreman_scc_manager/rubygem-foreman_scc_manager.spec
> +BuildRequires: %{?scl_prefix}rubygem(katello) >= 3.16
You can drop the foreman-tasks and rails deps on lines 30 & 31

2023-01-18 15:52 UTC, ekohl commented
Looks like the NPM packages aren't there:
```
DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(@babel/core) < 8.0.0
DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(@babel/core) >= 7.7.0
DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(@theforeman/builder) >= 4.0.0
DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(react-intl) < 3.0.0
DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(react-intl) >= 2.8.0
```

It really is hard to get this to work, given Foreman 3.3 is EOL so we're not going to make changes to those packages anymore.

If you want this to work, I'd recommend releasing a version that's compatible with the older NPM packages.

2023-02-16 08:55 UTC, nadjaheitmann commented
> Looks like the NPM packages aren't there:
> 
> ```
> DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(@babel/core) < 8.0.0
> DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(@babel/core) >= 7.7.0
> DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(@theforeman/builder) >= 4.0.0
> DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(react-intl) < 3.0.0
> DEBUG util.py:598:  Error: No Package found for rh-nodejs10-npm(react-intl) >= 2.8.0
> ```
> 
> It really is hard to get this to work, given Foreman 3.3 is EOL so we're not going to make changes to those packages anymore.
> 
> If you want this to work, I'd recommend releasing a version that's compatible with the older NPM packages.

@ekohl  Took me a while to finish this up, sorry about that. Now it seems to work. Is it still possible to merge? Would love to have it in Foreman 3.3 .

2023-02-16 11:45 UTC, ekohl approved these changes
I'd be OK with merging this, but do you need it in a release? For Katello that means we need to sign the RPM and kick of a release.

2023-02-16 11:52 UTC, nadjaheitmann commented
> I'd be OK with merging this, but do you need it in a release? For Katello that means we need to sign the RPM and kick of a release.

What exactly do you mean? It would be nice if the package was available in Foreman 3.3/Katello 4.5 repos.

2023-02-16 12:07 UTC, ekohl commented
Technically Foreman 3.3 and Katello 4.5 are already end of life, so we don't really publish anything in it anymore. We do have the pipelines in place because it can be useful to deal with upgrade issues. Unlike plugins the Katello releases are GPG signed and that means some manual work. So I can make an exception here, but it'd be preferred to focus on supported releases.

2023-02-16 12:18 UTC, nadjaheitmann commented
It is not my intention to put extra work on anybody, so next time feel free to remind me if I open PRs against unsupported versions :see_no_evil: For this, we both put in some effort in getting this straight and the PR ready. If you merge it now into foreman-packaging but it does not appear in the repos, then we have a diversion between foreman-packaging and the available packages in https://yum.theforeman.org/katello/4.5/ or am I misunderstanding something?

2023-02-16 12:21 UTC, ekohl commented
Correct. So let's merge & release this now and focus on supported releases next time.

2023-02-16 12:21 UTC, merged

2023-02-16 13:25 UTC, ekohl commented
Once https://ci.theforeman.org/job/katello-4.5-rpm-pipeline/17/ is green it should be available.

2023-02-16 13:26 UTC, nadjaheitmann commented
Thanks :+1: