Update foreman and drop rbvmomish
theforeman/foreman-packaging pull request #8994
Opened 2023-01-26 20:53 UTC by ehelms

When rubygem-rbvmomi2 was introduced, it also added rbvmomish which generates a conflict on disk when both are installed (https://community.theforeman.org/t/errors-installing-foreman-vmware/32072). I am opting to use the newer version rather than the older version.

2023-01-26 20:55 UTC, ekohl requested changes
Actually, we drop and obsolete `rubygem-rbvmomi`. I think they share the same namespace so you'd have more conflicts.

2023-01-27 02:05 UTC, ehelms commented
Updated -- what threw me off was that the foreman spec file still required rbvmomi. This change has two commits, one that updates the foreman spec dependencies, and a second that removes rbvmomi.

2023-01-27 07:05 UTC, evgeni commented on packages/foreman/foreman/foreman.spec
> +Requires: rubygem(rss)
This is ruby 3+ only and shouldn't be here (yet)

2023-01-27 07:05 UTC, evgeni commented
`rubygem-rbvmomi2` needs to obsolete `rubygem-rbvmomi`

2023-01-27 07:31 UTC, evgeni commented
I've took the liberty to implement these changes to get this going.

2023-01-27 09:08 UTC, ekohl approved these changes

2023-01-27 09:09 UTC, merged