Bump rubygem-foreman_webhooks to 3.1.0-1
theforeman/foreman-packaging pull request #9439
Opened 2023-05-25 15:18 UTC by ofedoren

ASMR: Another SCL Macros Removal.

Supported Versions:

- 3.6

2023-05-25 15:44 UTC, ekohl requested changes
Normally for stable branches we use cherry picks, to make sure they're in sync. So `git cherry-pick -x a76c3135b5e18b8f4e48d5bd0d23f0890d1d50c6`. But first I'd remove SCL macros in `rpm/develop` and then pick that along with it.

2023-05-26 06:25 UTC, evgeni commented
https://github.com/theforeman/foreman-packaging/pull/9440 was merged, so if you pick https://github.com/theforeman/foreman-packaging/commit/a76c3135b5e18b8f4e48d5bd0d23f0890d1d50c6 and https://github.com/theforeman/foreman-packaging/commit/d2bf8ffccf37b8890f9918e6587108edd9bc282b you'll get a clean git history and a working build :)

2023-05-26 13:02 UTC, ofedoren commented
Thank you, updated.

2023-06-28 08:25 UTC, evgeni approved these changes

2023-06-28 08:26 UTC, merged